server:
  port: '3000'

slack:
  appToken: 'xapp...'
  botToken: 'xoxb-xxxxxxxxx-xxxxxxxxxx-xxxxxxxxxxxx'
  signingSecret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

jira:
  apiToken: 'xxxxxxxxxxxxxxxxxxxxxxxx'
  baseUrl: 'https://jira.example.com'
  user: 'test'
